apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hpa-example
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hpa-example
  template:
    metadata:
      labels:
        name: hpa-example
        tier: backend
        type: php
    spec:
      containers:
        - name: hpa-example
          image: gsviec/hpa-example
          # command: 
          #   - docker-entrypoint.sh
          # args:
          #   - start
          # envFrom:
          # - configMapRef:
          #     name: env-all-modules
          # - configMapRef:
          #     name: env-all-golang
          # - configMapRef:
          #     name: env-hpa-example
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "200m"
            limits:
              memory: "100Mi"
              cpu: "300m"
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      # imagePullSecrets:
      # - name: registrypullsecret
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hpa-example
    type: php
    tier: backend
  name: hpa-example
spec:
  ports:
  - name: http-hpa-example
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: hpa-example
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
