apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
    type: golang
    tier: backend
  name: hello
spec:
  ports:
  - name: tcp-hello
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    name: hello
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}